"""Branded report rendering (spec Ch 11.2.4).

Beta renders the dealer-branded report as standalone HTML (printable to PDF from
the browser). Production re-renders the same template server-side via WeasyPrint
for the canonical download; the layout/section set here mirrors that 7-section
structure so the migration is a renderer swap, not a redesign."""
from __future__ import annotations

from datetime import datetime
from html import escape

AMBER = "#C8942A"
INK = "#1f2a37"


def _fmt(n, prefix="", suffix="", dp=0):
    if n is None:
        return "—"
    try:
        if n == -1:
            return "n/a"
        return f"{prefix}{n:,.{dp}f}{suffix}"
    except (TypeError, ValueError):
        return str(n)


def render_report_html(project: dict, comparison: dict, *, template: str = "sustainable_finishes_v1") -> str:
    baseline = comparison.get("baseline", {})
    films = comparison.get("films", [])
    estimate_mode = comparison.get("engine_mode") != "energyplus"
    warnings = comparison.get("warnings", [])

    # Recommend the best simple payback among films with positive savings.
    ranked = [f for f in films if f.get("delta_cost_usd_per_year", 0) > 0]
    recommended = min(ranked, key=lambda f: f.get("simple_payback_years", 1e9), default=(films[0] if films else {}))

    rows = ""
    for f in films:
        best = f is recommended
        rows += (
            f"<tr class='{'best' if best else ''}'>"
            f"<td>{escape(str(f.get('scenario_label','')))} "
            f"<span class='sku'>{escape(str(f.get('film_sku','')))}</span></td>"
            f"<td>{_fmt(f.get('delta_cooling_kwh'))}</td>"
            f"<td>{_fmt(f.get('delta_total_kwh'))}</td>"
            f"<td>{_fmt(f.get('delta_cost_usd_per_year'),'$')}</td>"
            f"<td>{_fmt(f.get('project_cost_usd'),'$')}</td>"
            f"<td>{_fmt(f.get('simple_payback_years'),'',' yr',1)}</td>"
            f"<td>{_fmt(f.get('npv_15yr_usd'),'$')}</td>"
            f"<td>{_fmt(f.get('irr_15yr_pct'),'','%',1)}</td>"
            f"<td>{_fmt(f.get('delta_co2_lb_per_year'),'',' lb')}</td>"
            f"</tr>"
        )

    banner = ""
    if estimate_mode:
        banner = (
            "<div class='warn'><strong>PRELIMINARY ESTIMATE.</strong> Generated by the "
            "analytical fallback engine — not an audited EnergyPlus run. Not valid for "
            "bid submission, utility rebate filing, or LEED.</div>"
        )

    rec_savings = _fmt(recommended.get("delta_cost_usd_per_year"), "$") if recommended else "—"
    rec_payback = _fmt(recommended.get("simple_payback_years"), "", " yr", 1) if recommended else "—"
    rec_co2 = _fmt(recommended.get("delta_co2_lb_per_year"), "", " lb") if recommended else "—"
    rec_peak = _fmt(recommended.get("delta_peak_kw"), "", " kW", 1) if recommended else "—"

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>Energy Savings Analysis — {escape(project.get('name',''))}</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:{INK};margin:0;padding:40px;max-width:900px;margin:0 auto}}
 header{{border-bottom:3px solid {AMBER};padding-bottom:16px;margin-bottom:24px;display:flex;justify-content:space-between;align-items:flex-end}}
 h1{{font-size:24px;margin:0}} h2{{color:{AMBER};font-size:15px;letter-spacing:.08em;text-transform:uppercase;margin-top:32px}}
 .brand{{color:{AMBER};font-weight:700;letter-spacing:.15em;font-size:13px}}
 .tiles{{display:flex;gap:16px;margin:16px 0}}
 .tile{{flex:1;background:#f7f5f0;border:1px solid #eee;border-radius:10px;padding:16px;text-align:center}}
 .tile .v{{font-size:26px;font-weight:700;color:{INK}}} .tile .l{{font-size:12px;color:#666;margin-top:4px}}
 table{{width:100%;border-collapse:collapse;font-size:13px;margin-top:8px}}
 th,td{{padding:8px 10px;text-align:right;border-bottom:1px solid #eee}} th:first-child,td:first-child{{text-align:left}}
 thead th{{background:{INK};color:#fff;font-weight:600}}
 tr.best{{background:#fbf4e4}} tr.best td:first-child{{font-weight:700}}
 .sku{{color:#999;font-weight:400;font-size:11px}}
 .warn{{background:#fff4f4;border:1px solid #f3c2c2;color:#7a1f1f;padding:12px 14px;border-radius:8px;margin:16px 0;font-size:13px}}
 .meta{{font-size:12px;color:#666;line-height:1.7}} footer{{margin-top:40px;border-top:1px solid #eee;padding-top:12px;color:#999;font-size:11px}}
</style></head><body>
<header>
 <div><div class="brand">SUSTAINABLE FINISHES</div><h1>Window Film Energy Savings Analysis</h1></div>
 <div class="meta" style="text-align:right">{escape(project.get('name',''))}<br>{escape(project.get('city') or '')} {escape(project.get('state') or '')} {escape(project.get('zip',''))}<br>{datetime.utcnow():%B %d, %Y}</div>
</header>
{banner}
<h2>Executive Summary</h2>
<p>Recommended option: <strong>{escape(str(recommended.get('scenario_label','—')))} ({escape(str(recommended.get('film_sku','')))})</strong>.
This analysis compares the existing glazing against {len(films)} candidate 3M film(s) using the EnergyPlus whole-building method.</p>
<div class="tiles">
 <div class="tile"><div class="v">{rec_savings}</div><div class="l">Annual savings</div></div>
 <div class="tile"><div class="v">{rec_payback}</div><div class="l">Simple payback</div></div>
 <div class="tile"><div class="v">{rec_peak}</div><div class="l">Peak demand cut</div></div>
 <div class="tile"><div class="v">{rec_co2}</div><div class="l">CO2 avoided / yr</div></div>
</div>
<h2>Inputs</h2>
<div class="meta">
 Building type: {escape(project.get('building_type',''))} &nbsp;|&nbsp; Floor area: {_fmt(project.get('gross_floor_area_sf'))} sf<br>
 Climate zone: {escape(project.get('climate_zone',''))} &nbsp;|&nbsp; Weather station: {escape(str(baseline.get('weather_station','')))}<br>
 Utility rate: {_fmt(project.get('utility_rate_usd_kwh'),'$','/kWh',4)} &nbsp;|&nbsp; eGRID subregion: {escape(project.get('egrid_subregion',''))}
</div>
<h2>Per-Film Results</h2>
<table><thead><tr><th>Scenario</th><th>&#916;Cooling kWh</th><th>&#916;Total kWh</th><th>$/yr</th><th>Project cost</th><th>Payback</th><th>NPV (15yr)</th><th>IRR</th><th>CO2/yr</th></tr></thead>
<tbody>{rows}</tbody></table>
<h2>Methodology</h2>
<div class="meta">Engine: {escape(str(baseline.get('energyplus_version','')))} &nbsp;|&nbsp; Glazing optics: LBNL IGSDB &nbsp;|&nbsp; Weather: NREL NSRDB/TMY3 &nbsp;|&nbsp; Carbon: EPA eGRID 2023.
Economics: 15-yr life, 5% discount, 2.5% utility escalation (all user-overridable). See the accompanying audit bundle (.zip) for raw EnergyPlus inputs and outputs.</div>
{('<div class="meta" style="margin-top:8px">' + '<br>'.join(escape(w) for w in warnings) + '</div>') if warnings else ''}
<footer>Generated by EnergyModeler · template {escape(template)} · open-methodology EnergyPlus wrapper</footer>
</body></html>"""
